version: "3"
services:
  springrest:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: #links:
      - docker_db
    ports:
      - "9000"
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:postgresql://docker_db:5432/project3_consumer_db"}'
    restart:  always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springrest
    ports:
      - "8080:8080"
  docker_db:
    #image: postgres
    build:
      context: .
      dockerfile: ./db_dockerfile/Dockerfile
    volumes:
      - ./PSDB/API_db/data_API/db:/var/lib/postgresql/data
    command: -p 5432
    env_file:
      - .psg_env 
    restart:  always