# dataSource configs
spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project3_consumer_db

# Hibernate configs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
# in order to allow HTTP methods PUT, PATCH, DELETE 
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
application:
  hash: 
    salt: randomChars
    
    

